Mysql:
  Ip: "115.190.43.83"
  Port: 3306
  User: "root"
  Password: "4ay1nkal3u8ed77y"
  Db: "p2308a"

Redis:
  Addr: "115.190.43.83:6379"
  Password: "4ay1nkal3u8ed77y"
  Db: 0
  MaxIdle: 10
  PoolSize: 100